export {default as LandpagePage} from './Landpage'
export {default as LoginPage} from './Login'
export {default as RegisterPage} from './Register'
export {default as ProfilePage} from './Profile'
export {default as ClientListPage} from './ClientList'
export {default as SchedulesListPage} from './SchedulesList'
export {default as AlbunsPage} from './Albuns'
export {default as MainClientPage} from './MainClient'